
spring:
  application:
    name: notification-manager

  data:
    mongodb:
      database: soshealth
      uri: mongodb://soshealth:oUoGMmS5r4gPGltAoiT10bJsCnEsNrTQZZNM4veYjjtVSAsrbmlDXuZTewRdCKreWZdIZ79iglWttqR6gUArMw==@soshealth.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@soshealth@

messaging:
  twilio:
    accountSid: ACaabaf7514b819edceeddecbe5975a155
    authToken: e1a42725e782a28545cbeb1c7ec34f87
    fromNumber: +19207988494


server:
  servlet:
    context-path: /notification/v1
  http2:
    enabled: true
  port: 443